ant-design/pro-table

- src/Table.tsx
when set paginations->showSizeChanger = true, the sizeChanger not work， cannot change pagesize.
> fix pageSize not work when enable showSizeChanger

- README.en_US.md
- README.md
- docs/api.md
- docs/demo/batchOption.tsx
- docs/demo/search.tsx
- docs/demo/single.tsx
- docs/search.md
- package.json
- src/Form/index.tsx
- src/Table.tsx
- src/useFetchData.tsx
fix https://github.com/ant-design/pro-table/issues/15
> Api suggestion

- src/Form/index.tsx
> feat: wrap search buttons in a Form.Item

- docs/search.md
> doc: fix minor syntax errors. 

- README.en_US.md
- README.md
- docs/api.md
- docs/search.md
- src/Table.tsx
- src/useFetchData.tsx
在数据请求失败时捕获错误并抛到组件外。
```js
<ProTable
...
onRequestError={e => {
console.log(e)
}}
/>
```
> feat: invoke onRequestError when fetching data failed

- src/Table.tsx
> bugfix: 点击表单搜索或重置的时候没有每次触发fetchList

- src/Table.tsx
- src/component/alert/index.tsx
key="0" 
Warning: Each child in a list should have a unique "key" prop
> Warning: Each child in a list should have a unique "key" prop and Warning: `NaN` is an invalid value for the `width` css style property.

- docs/search.md
> doc: remove duplicated beforeSearchSubmit. Fixes #137

- src/index.less
https://github.com/ant-design/pro-table/pull/150
> 选择框没有对齐（重新提PR）

- src/Table.tsx
> fix type define for tableAlertRender

- src/component/intlContext/index.tsx
- src/index.tsx
- src/locale/es_ES.tsx
Support for Spanish language :)
> add locale for spanish language

- README.en_US.md
- README.md
- docs/api.md
- src/Table.tsx
1. 在action中暴露clearSelected方法
1. 修复本地数据源selectedRows无值问题 #231
> 🐛 bug: fix selectedRows no work problem

- src/Form/index.less
- src/Table.tsx
- src/component/alert/index.less
- src/component/columnSetting/index.less
- src/component/dropdown/index.less
- src/component/indexColumn/index.less
- src/component/status/index.less
- src/component/toolBar/index.less
- src/index.less
ref ant-design/ant-design-pro#6166
两边的名字重复了，导致 antd的 table 被覆盖
> 🐛 bug: remame variable not duplicates with antd

- README.en_US.md
- README.md
- docs/api.md
close https://github.com/ant-design/pro-table/issues/263
> 📝 docs: docs update

- src/defaultRender.tsx
> 🐛bugfix: fix valueType funtion params problem

- docs/api.md
- docs/demo/valueType.tsx
- docs/example.md
- docs/example/dataSource.tsx
- docs/example/pollinga.tsx
- docs/intl.md
- docs/search.md
- docs/select.md
- docs/valueType.md
- src/Table.tsx
- src/container.tsx
- src/useFetchData.tsx
提升信息密度，默认设置为中等大小，默认显示 size change 和 total
-------------
Improve the information density, the default setting is medium size, and the default display size change and total
close https://github.com/ant-design/pro-table/issues/269
> 🐲 format: increase information density

- src/Form/index.tsx
close https://github.com/ant-design/pro-table/issues/281
> 🐛 bug: fix delete unnecessary fields

- docs/demo/linkage_form.tsx
- docs/search.md
- src/Form/FormOption.tsx
- src/Form/index.tsx
- src/Table.tsx
close https://github.com/ant-design/pro-table/issues/289
close https://github.com/ant-design/pro-table/issues/267
close https://github.com/ant-design/pro-table/issues/277
use
```
renderFormItem: (_, { type, defaultRender, ...rest }, form) => {
if (type === "form") {
return null;
}
// 获取其他的值
const status = form.getFieldValue("state");
if (status !== "open") {
return <Input {...rest} placeholder="请输入" />;
}
// 使用默认的 demo
return defaultRender(_);
};
```
> 💥 feat: support linkage between forms

- src/index.tsx
Signed-off-by: PangZhiGang <xiaopanghhh@163.com>
> fix 新增加的繁体中文的国际化没有导出。

- README.en_US.md
- README.md
- docs/demo/batchOption.tsx
- docs/demo/linkage_form.tsx
- docs/demo/search.tsx
- docs/demo/search_option.tsx
- docs/demo/single.tsx
- docs/demo/valueType.tsx
- docs/example/columnsStateMap.tsx
- docs/example/dataSource.tsx
- docs/example/pollinga.tsx
- docs/example/search.tsx
- docs/select.md
- docs/valueType.md
- package.json
- src/Form/FormOption.tsx
- src/Form/index.tsx
- src/Table.tsx
- src/component/columnSetting/index.tsx
- src/component/dropdown/index.tsx
- src/component/intlContext/index.tsx
- src/component/toolBar/index.tsx
- src/component/util.tsx
- src/index.tsx
- src/useFetchData.tsx
- tests/__tests__/demo.tsx
- tests/__tests__/index.test.tsx
close https://github.com/ant-design/pro-table/issues/318
> 💥 feat: if not configured, hide toolbar automatically

- docs/demo/valueType.tsx
- src/component/util.tsx
- src/useFetchData.tsx
close https://github.com/ant-design/pro-table/issues/305
> ⚡️ performance: Network request to increase debounce

- src/Form/index.tsx
close https://github.com/ant-design/pro-table/issues/321
> 🐛 bug: Fix the problem that the form is called before use

- src/Form/FormOption.tsx
- src/Table.tsx
- src/component/columnSetting/index.tsx
- src/component/toolBar/index.less
- src/component/toolBar/index.tsx
- src/index.less
> 💄 UI : Use Space to modify spacing

- docs/demo/valueTypeDate.tsx
- docs/demo/valueTypeNumber.tsx
- docs/valueType.md
- src/Form/index.less
- src/defaultRender.tsx
> 💥 feat: support value type for code

- docs/demo/batchOption.tsx
- src/Table.tsx
- src/component/ErrorBoundary.tsx
close https://github.com/ant-design/pro-table/issues/356
> 💄 UI : add ErrorBoundary page

- src/Table.tsx
close https://github.com/ant-design/pro-table/issues/339
> 🐛bug: dataSource.filter adds non-null verification

- docs/demo/valueType.tsx
- docs/demo/valueTypeDate.tsx
- docs/demo/valueTypeNumber.tsx
- docs/valueType.md
- src/defaultRender.tsx
> 💥 feat: value type support avatar

- src/defaultRender.tsx
> fix: if text is number should not return "-"

- src/Form/index.tsx
close https://github.com/ant-design/pro-table/issues/388
close https://github.com/ant-design/pro-table/issues/349
> 💥 feat: support renderItem onChange

- docs/api.md
- src/Form/FormOption.tsx
- src/Form/index.tsx
- src/Table.tsx
```jsx
<ProTable
onReset={() => { console.log('onReset') }}
type="form"
/>
```
> feat: add onReset

- src/Table.tsx
- src/defaultRender.tsx
- src/useFetchData.tsx
close  https://github.com/ant-design/pro-table/issues/420
> 🐛 bug: Fixed an issue where the page number changed from large to small

- src/Table.tsx
> 🐛  bugfix: default query has initialValues

- docs/example/intl.tsx
- src/Form/index.tsx
- src/component/intlContext/index.tsx
- src/component/util.tsx
- src/locale/en_US.tsx
- src/locale/es_ES.tsx
- src/locale/it_IT.tsx
- src/locale/ja_JP.tsx
- src/locale/ms_MY.tsx
- src/locale/ru_RU.tsx
- src/locale/vi_VN.tsx
- src/locale/zh_CN.tsx
- src/locale/zh_TW.tsx
> 💥 feat: add money Symbol i18n

- docs/api.md
- docs/demo/valueType.tsx
- docs/search.md
- src/Table.tsx
- src/component/util.tsx
```
request={(params, sorter, filter) => {
console.log(params, sorter, filter);
return Promise.resolve({
total: 200,
data: tableListDataSource,
success: true,
});
}}
```
> 💥 feat: request support sort and filter

- src/Form/index.tsx
- src/Table.tsx
close https://github.com/ant-design/pro-table/issues/433
> Don't empty all items when the data source is updated

- src/Table.tsx
- src/component/util.tsx
close https://github.com/ant-design/pro-table/issues/485
> 🐛 bug: fix width is string throw some error

- .umirc.js
- docs/index.md
- src/component/columnSetting/index.tsx
- 增加feature 部分，高亮pro-table 的特性
- 去掉有些冗余的badge
- nav增加github 链接
> chore: 优化站点

- docs/demo/valueType.tsx
- src/Table.tsx
- src/component/util.tsx
close https://github.com/ant-design/pro-table/issues/526
close https://github.com/ant-design/pro-table/issues/522
> 🐛  bugfix: default render support number

- src/Table.tsx
> 🐛 bug: fix selectedRows repeat problem

- README.md
- docs/api.md
- docs/demo/search.tsx
- docs/getting-started.md
- docs/index.md
- docs/search.md
- src/Form/index.tsx
- src/Table.tsx
- src/defaultRender.tsx
close https://github.com/ant-design/pro-table/issues/548
```
title: (_, type) => (type === 'table' ? '状态' : '列表状态'),
```
> 💥 feat: support title is a function

- src/Form/index.tsx
clearIcon应该要返回ReactNode，[#563]这个clearIcon是不小心加错了吧？
> bugfix:移除掉查询条件中Select的clearIcon属性

- README.en_US.md
- README.md
- docs/api.md
- docs/demo/batchOption.tsx
- docs/demo/linkage_form.tsx
- docs/demo/search.tsx
- docs/demo/search_option.tsx
- docs/demo/single.tsx
- docs/demo/valueType.tsx
- docs/example/columnsStateMap.tsx
- docs/example/dataSource.tsx
- docs/example/form.tsx
- docs/example/intl.tsx
- docs/example/pollinga.tsx
- docs/example/search.tsx
- docs/search.md
- src/Form/index.tsx
- src/Table.tsx
- src/component/ErrorBoundary.tsx
- tests/__tests__/demo.tsx
默认不显示表头的筛选菜单项，在 Columns Item 中配置 showFilters 可以显示。
> feat: filters default empty

- README.md
- docs/api.md
- docs/search.md
> 修复submitText文档的描述和默认值

- README.en_US.md
- README.md
- docs/api.md
- docs/demo/batchOption.tsx
- docs/demo/linkage_form.tsx
- docs/demo/search.tsx
- docs/demo/search_option.tsx
- docs/demo/single.tsx
- docs/demo/valueType.tsx
- docs/example/columnsStateMap.tsx
- docs/example/dataSource.tsx
- docs/example/form.tsx
- docs/example/intl.tsx
- docs/example/pollinga.tsx
- docs/example/search.tsx
- docs/search.md
- package.json
- src/Table.tsx
- tests/__tests__/demo.tsx
1、移除 showFilters api
2、扩展 antd 配置 filters，当值为 true 时，自动使用 valueEnum 生成
> Filters default empty

- src/Table.tsx
- src/component/alert/index.less
- src/container.tsx
- 样式修改
- 修复eslint 升级带来的更严格hook 校验报错等CI问题
> 💅style: alert 宽度100%

- src/component/intlContext/index.tsx
- src/locale/fr_FR.tsx
Nothing crazy, just French locale added 🙏  🇫🇷
> Added French language support

- docs/example.md
- docs/example/renderTable.tsx
- src/Table.tsx
- src/index.less
close https://github.com/ant-design/pro-table/issues/621
> 💥 feat:support more renderAPI

- src/component/toolBar/index.tsx
close https://github.com/ant-design/pro-table/issues/649
> 🐛 bug: headerTitle should alway have

- src/component/toolBar/index.less
- src/form/index.less
close https://github.com/ant-design/pro-table/issues/640
> 💄 UI: better phone mode style

- src/component/status/index.tsx
- src/component/util.tsx
> valueEnum支持自定义色值,status值不区分大小写
